model:
  name: 'M_01_ISFM'
  n_patches: 128
  


  embedding: E_com_00_PE
  embed_type: 'data'  # 嵌入类型
  patch_size_L: 256
  patch_size_C: 1

  stride: 16              # 步长
  padding: 2              # 填充
  output_dim: 1024

  backbone: B_01_basic_transformer
  # input_dim: 1024
  nhead: 1
  num_layers: 1

  task_head: H_01_Linear_cla
  dropout: 0


trainer:

  n_epochs: 20
  cla_loss: 'CE'


  device: cuda
  gpus: 1 
  precision: 16
  
  seed: 42
  monitor: 'val_loss'
  patience: 64
  # loss
  lr: 0.0001
  weight_decay: 0.0001 
  snr: False
  wandb: False
  notes: 'basic'
  metrics: ['acc', 'f1']
  # prune
  pruning: False
  regularization:
    flag: False
    method: 
      l1: 0.00001

dataset:
  data_dir: 'a_000_simulation' # '/home/user/data/a_bearing/a_006_THU_pro/LQ_fusion/'
  task: a_000_simulation # THU_006_basic THU_006_generalization THU_006_fusion THU_018_basic THU_018_generalization THU_018_fusion
  target: '10hz' # if basic or generalization 1hz 10hz 15hz
  batch_size: 64
  num_workers: 4
  f_s: 1024 # 25600 
  n_classes: 7