model:
  # configs/HSE_paper/ablation/enlarged_patch.yaml
  name: 'M_01_ISFM'
  embedding: 'E_01_HSE_abalation'
  patch_size_L: 256
  patch_size_C: 1
  n_patches: 128
  output_dim: 1024
  backbone: B_01_basic_transformer
  nhead: 2
  num_layers: 1
  task_head: H_01_Linear_cla
  dropout: 0
  sampling_mode: 'random'
  apply_mixing: true
  linear_config: [1, 1]
  patch_scale: [1, 1, 0.5]
  activation_type: 'silu'


trainer:
  n_epochs: 100

  cla_loss: 'CE'
  imputation_loss: 'MSE'
  forecast_loss: 'MSE'
  anomaly_loss: 'MSE'

  device: cuda
  gpus: 1 
  precision: 16
  
  seed: 42
  monitor: 'val_loss'
  patience: 64
  # loss
  lr: 0.0001
  weight_decay: 0.0001 
  snr: False
  wandb: True
  notes: 'basic'
  metrics: ['acc', 'f1']
  # prune
  pruning: False
  regularization:
    flag: False
    method: 
      l1: 0.001
  pretrained_weight: False
  scheduler: 'reduceonplateau'
  optimizer: 'adam'

dataset:
  batch_size: 256
  num_workers: 4
  train_val_rate: 0.8 
  task_name: HSE_paper
  task:
    a_006_THU:
      data_dir: '/home/user/data/a_bearing/a_006_THU_pro/LQ_fusion/'
      source: ['1hz','15hz'] # if basic or generalization 1hz 10hz 15hz 
      target: '10hz' # if basic or generalization 1hz 10hz 15hz
      task_list: ['classification'] # imputation
      n_classes: 4
      f_s: 25600
      length: 4096
    a_001_CWRU:
      data_dir: '/home/user/data/a_bearing/a_001_CWRU_pro/'
      source: ['CWRU_12kHz_1730rpm_3hp_10','CWRU_12kHz_1797rpm_0hp_10',
      'CWRU_48kHz_1730rpm_3hp_10','CWRU_48kHz_1797rpm_0hp_10'] # if basic or generalization 1hz 10hz 15hz 
      target: ['CWRU_12kHz_1750rpm_2hp_10','CWRU_12kHz_1772rpm_1hp_10',
      'CWRU_48kHz_1750rpm_2hp_10','CWRU_48kHz_1772rpm_1hp_10'] # if
      task_list: ['classification'] # imputation
      n_classes: 10
      f_s: 12000
      length: 4096
    a_013_SUDA:
      data_dir: '/home/user/data/a_bearing/a_013_SUDA_pro/'
      source: ['SUDA_bearing_0kN_16','SUDA_bearing_3kN_16'] # if basic or generalization 1hz 10hz 15hz 
      target: ['SUDA_bearing_1kN_16','SUDA_bearing_2kN_16'] # if
      task_list: ['classification'] # imputation
      n_classes: 16
      f_s: 10000


    

