model:
  name: 'M_01_ISFM'
  n_patches: 64
  n_classes: 4
  f_s: 100

  embedding: E_01_HTFE
  patch_size_L: 128
  patch_size_C: 8
  output_dim: 64

  backbone: B_01_basic_transformer
  input_dim: 64
  nhead: 2
  num_layers: 2

  task_head: H_01_Linear_cla
  dropout: 0


trainer:

  n_epochs: 100
  loss_type: 'CE'


  device: cuda
  gpus: 1 
  precision: 16
  
  seed: 42
  monitor: 'val_loss'
  patience: 64
  # loss
  lr: 0.001
  weight_decay: 0.0001 
  snr: False
  wandb: False
  notes: 'basic'
  metrics: ['acc', 'f1']
  # prune
  pruning: False
  regularization:
    flag: False
    method: 
      l1: 0.00001


  
dataset:
  data_dir: '/home/user/data/a_bearing/a_006_THU_pro/LQ_fusion/'
  task: a_006_THU # THU_006_basic THU_006_generalization THU_006_fusion THU_018_basic THU_018_generalization THU_018_fusion
  target: '10hz' # if basic or generalization 1hz 10hz 15hz
  batch_size: 64
  num_workers: 4